### ISSUE TITLE
魅族解析包错误，魅族16x 系统8.1，是不是地址最好要改成外部存储

### ISSUE THREAD

**Issue by HelloJokerWord** [kelinZhou/ApkUpdater#1]
java.lang.SecurityException: Permission Denial: reading com.atgc.apkupdate.provider.AppFileProvider uri content://com.atgc.mycs.fileProvider/./Android/data/com.atgc.mycs/files/Download/com.atgc.mycs2019-5-10_17-05.apk from pid=3930, uid=10033 requires the provider be exported, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:709)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:532)
        at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:523)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:451)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:302)
        at android.os.Binder.execTransact(Binder.java:702)

**Comment by kelinZhou** [comment]
请问一下你用的是最新版的依赖吗？发自我的华为手机-------- 原始邮件 --------主题：[kelinZhou/ApkUpdater] 魅族解析包错误，魅族16x 系统8.1，是不是地址最好要改成外部存储 (#1)发件人：贺小斌 收件人：kelinZhou/ApkUpdater 抄送：Subscribed java.lang.SecurityException: Permission Denial: reading com.atgc.apkupdate.provider.AppFileProvider uri content://com.atgc.mycs.fileProvider/./Android/data/com.atgc.mycs/files/Download/com.atgc.mycs2019-5-10_17-05.apk from pid=3930, uid=10033 requires the provider be exported, or grantUriPermission()
at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:709)
at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:532)
at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:523)
at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:451)
at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:302)
at android.os.Binder.execTransact(Binder.java:702)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kelinZhou/ApkUpdater/issues/1",
"url": "https://github.com/kelinZhou/ApkUpdater/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
